### PR TITLE
Removing all lines in delete-kind-cluster containing OVERRIDE_PATH

### PR DESCRIPTION
**Pull request by tbutler4**
Issue #, if available:
No issue but requested in #533 
Description of changes:
I simply deleted any lines mentioning OVERRIDE_PATH.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tbutler4** [comment]
To confirm.. Is this what you were suggesting? @jaypipes 

I am also hoping to attempt the rest of the requests #504 if possible.

**Comment by jaypipes** [comment]
> To confirm.. Is this what you were suggesting to delete? @jaypipes
> 
> I am also hoping to attempt the rest of the requests in #504 if possible.

Yup. Precisely :)

**Review by jaypipes — APPROVED** [review]
:+1:

**Comment by jaypipes** [comment]
@tbutler4 please coordinate with @niconosenzo, who is also working on #504 :) there's tons of work for two of you to work on. Just make sure not to step on each other's toes!

**Comment by tbutler4** [comment]
> @tbutler4 please coordinate with @niconosenzo, who is also working on #504 :) there's tons of work for two of you to work on. Just make sure not to step on each other's toes!

@jaypipes I agree with you and will stick to what is asked. I can't begin to explain my excitement to have just contributed to AWS. So thank you for being involved as well.

**Comment by jaypipes** [comment]
> > @tbutler4 please coordinate with @niconosenzo, who is also working on #504 :) there's tons of work for two of you to work on. Just make sure not to step on each other's toes!
> 
> @jaypipes I agree with you and will stick to what is asked. I can't begin to explain my excitement to have just contributed to AWS. So thank you for being involved as well.

Welcome to the ACK contributor club, @tbutler4! :) If you're looking for other things to help out on, hit me up on Kubernetes community Slack in the #provider-aws channel. Happy to hop on a video call or something to give you the lay of the land.

**Pull request merged**
