### PR TITLE
 Re-generate all services via ack-generate by running make build-controller

### PR DESCRIPTION
**Pull request by ricardo-larosa**
Description of changes:

Regenerate all services via `ack-generate` by running `make build-controller SERVICE=<service>`
This action:
1. Generate `kustomization.yaml` files under `config/crd` using as resource all crds under `config/crd/bases`
2. Uncomment `crds` in all `config/default/kustomization.yaml` files
3. Update generated code by `ack-generate`, some of these changes come from https://github.com/aws/aws-controllers-k8s/pull/412

_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

### CODE REVIEW

**Comment by ricardo-larosa** [comment]
Open question: Do you think it might be helpful to follow up with a github action that verifies if the generated code was checked-in?

**Comment by jaypipes** [comment]
> Open question: Do you think it might be helpful to follow up with a github action that verifies if the generated code was checked-in?

Not at the moment, no. Perhaps later on.

**Comment by jaypipes** [comment]
@ricardo-larosa I'd like to regenerate the service controllers Go code in a separate commit and then leave this commit to just the generation of the CRD stuff. Give me a couple hours and then you can rebase.

**Comment by jaypipes** [comment]
LOL, never mind, I forgot I already merged the crd template fix :)

**Review by jaypipes — APPROVED** [review]
:+1:

**Comment by ricardo-larosa** [comment]
Cool Thanks!

**Pull request merged**
