### PR TITLE
removed getopts strategy from kind-build-test.sh

### PR DESCRIPTION
**Pull request by niconosenzo**
Efforts part of Issue #504
Refactoring stage: Argument variable values as env variables instead of getopts strategy
Script: kind-build-test.sh

Description of changes:
- Replaced getopts strategy with a fixed number of arguments (aws service name ) and env variable.
- Note that AWS_ROLE_ARN is defined as a variable during script startup:
`AWS_ROLE_ARN=${AWS_ROLE_ARN:-""}`
The above will cause the script to not fail even when the environment variable (previously passed as script argument) is not explicitly defined. I assumed this is intentional.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
Nice work @niconosenzo! :)

**Comment by RedbackThomson** [comment]
This appears to have broken the `make kind-test` target - which is failing our automated testing.

**Comment by RedbackThomson** [comment]
Further, I found an `echo` that still references the old command line arguments - https://github.com/aws/aws-controllers-k8s/blob/main/scripts/kind-build-test.sh#L59

There may be more, that I missed.

**Comment by niconosenzo** [comment]
> Further, I found an `echo` that still references the old command line arguments - https://github.com/aws/aws-controllers-k8s/blob/main/scripts/kind-build-test.sh#L59
> 
> There may be more, that I missed.

I will change that line on a separate PR, it doesn't look like there are more out there.

**Comment by niconosenzo** [comment]
> This appears to have broken the `make kind-test` target - which is failing our automated testing.

The PR should have not modified anything but only the way it's called. You may probably create an issue, I will take a look

**Comment by RedbackThomson** [comment]
> > This appears to have broken the `make kind-test` target - which is failing our automated testing.
> 
> The PR should have not modified anything but only the way it's called. You may probably create an issue, I will take a look

It did not modify the Makefile, but the Makefile references the old getopts version of this script.

**Pull request merged**
