### PR TITLE
Fix integration test automation

### PR DESCRIPTION
**Pull request by RedbackThomson**
Issue #, if available:

Description of changes:
Attempting to fix automation of integration tests, don't want shell script tests to use Dockerfile.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jaypipes** [comment]
@RedbackThomson am I missing something here? :) What is this fixing?

**Comment by RedbackThomson** [comment]
> @RedbackThomson am I missing something here? :) What is this fixing?

Nothing yet. Still running things locally. I was going to push a commit and then decided no to lol

**Comment by RedbackThomson** [comment]
Okay now it's ready for review. I really don't like this duplication of code, but I don't see a good way to fork (to go into a Docker container, or to run locally) any way else.

**Comment by RedbackThomson** [comment]
Any good way to run E2E tests in GH actions on the PR?

**Comment by jaypipes** [comment]
> Any good way to run E2E tests in GH actions on the PR?

unfortunately not yet. we used to have them run on each PR but there was a security issue with that. now, only possible to run the e2e tests manually under "Actions" -> "e2e tests

**Review by jaypipes — APPROVED** [review]

**Pull request merged**
