### PR TITLE
Start of CODEOWNERS, specifically for Amazon SageMaker Directories

### PR DESCRIPTION
**Pull request by mbaijal**
### Description of changes:
Added a simple codeowners file which - 
 - Currently, will notify the owners in case of changes to any of the directories they own
 - [TODO] Can be used to gate code merge on a review from a code owner by [enabling this setting on a protected branch](https://github.blog/2017-07-06-introducing-code-owners/#an-extra-layer-of-code-security). 

Note: 
 - Does each (some) of us need additional permission in order to be a codeowner.
 - Ideally we should use Github Teams to set these owners for a specific service
 - I have not set any global owners yet.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
Are we able to reference teams with the [AWS organisation](https://github.com/aws)?

**Comment by mbaijal** [comment]
> Are we able to reference teams with the [AWS organisation](https://github.com/aws)?

Probably ? Is there a way to test this without merge? I can change it to @aws/sagemaker-operator

**Review by jaypipes — APPROVED** [review]
@mbaijal I'm good with this if you guys are. Please do rebase and squash your commits into one, though please! :)

**Comment by mbaijal** [comment]
@surajkota @akartsky @RedbackThomson ok to merge ?

**Comment by surajkota** [comment]
ok to merge but I think repos are being migrated so not sure if this is needed

**Comment by jaypipes** [comment]
> ok to merge but repos are being migrated so not sure if this is needed

@mbaijal would you mind making a PR to the new github.com/aws-controllers-k8s/sagemaker-controller repository please? I'll fast merge the PR once I see it.

**Pull request closed without merging**
