### PR TITLE
add separate how-it-works and overview

### PR DESCRIPTION
**Pull request by jaypipes**
Adds a new birdseye view diagram and restructures the index.md file in
the docs.

Separates the "How it works" details into a separate doc page with a
more detailed diagram, along with an explanation of the steps outlined
in the diagram.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jaypipes** [comment]
Reviewers, please see formatted docs here:

https://github.com/jaypipes/aws-controllers-k8s/blob/docs/docs/contents/index.md
https://github.com/jaypipes/aws-controllers-k8s/blob/docs/docs/contents/how-it-works.md

**Comment by jaypipes** [comment]
@A-Hilaly fancy reviewing this in your morning? :)

**Review by tabern — APPROVED** [review]
/lgtm

**Review by A-Hilaly — APPROVED** [review]
/lgtm 👍

**Pull request merged**
